
%⃗q(t)=􏱵vc,x(t),vc,y(t),vc,z(t),xc(t),yc(t),zc(t),ωx,ωy,ωz,R0(t),R1(t),R2(t),R3(t)􏱶T



function [qent] = q (vitesse, position, vitesseAngulaire, R)

qent = [vitesse(1); vitesse(2); vitesse(3); ...
        position(1); position(2); position(3); ...
        vitesseAngulaire(1); vitesseAngulaire(2); vitesseAngulaire(3); ...
        R(1,1); R(1,2); R(1,3); ... 
        R(2,1); R(2,2); R(2,3) ...
        R(3,1); R(3,2); R(3,3)];

endfunction
